const express       = require('express')
const app           = express()
const defaultRoutes = express.Router()
const axios         = require('axios')

let User = require('../models/User')

defaultRoutes.route('/').get(function (req, res) {
    res.render('index', {title: 'Home', message: 'A Vulnerable Node & Mongo App'})
})

defaultRoutes.route('/reset').get(function (req, res) {
    User.deleteMany({}, function (err) {})
    users = [
        {
            username:   'admin',
            password:   '2TR6uTRAuMUr5vARs9fYgdqY',
            first_name: '',
            last_name:  '',
            role:       'admin',
            email:      'admin@gmail.com',
        },
        {
            username:   'guest',
            password:   'password',
            first_name: '',
            last_name:  '',
            role:       'guest',
            email:      'guest@gmail.com',
        },
        {
            username:   'ghost',
            password:   'abc123',
            first_name: 'bla',
            last_name:  'Ghost',
            role:       'user',
            email:      'ghost@gmail.com',
        },
        {
            username:   'jasmine',
            password:   'SuPeRsEcR3T',
            first_name: 'jasmine',
            last_name:  'bla',
            role:       'user',
            email:      'jasmine@gmail.com',
        },
        {
            username:   'angrybird',
            password:   'L1g7tM3Up!',
            first_name: 'Gary',
            last_name:  'Jorgen',
            role:       'user',
            email:      'prismman@gmail.com',
        },
        {
            username:   'sanear0',
            password:   'rEsfbA',
            first_name: 'Shaine',
            last_name:  'Anear',
            role:       'Marketing Manager',
            email:      'sanear0@sfgate.com',
        },
        {
            username:   'hstreet1',
            password:   'RqL0gSVLyr',
            first_name: 'Helge',
            last_name:  'Street',
            role:       'Biostatistician II',
            email:      'hstreet1@youtu.be',
        },
        {
            username:   'goldridge2',
            password:   'EMKQiro',
            first_name: 'Glen',
            last_name:  'Oldridge',
            role:       'Occupational Therapist',
            email:      'goldridge2@tripod.com',
        },
        {
            username:   'rmacauley3',
            password:   'cxz07bc',
            first_name: 'Ralf',
            last_name:  'Macauley',
            role:       'Senior Cost Accountant',
            email:      'rmacauley3@google.es',
        },
        {
            username:   'nbroxap4',
            password:   'TUImP8tGyOAk',
            first_name: 'Nelson',
            last_name:  'Broxap',
            role:       'Food Chemist',
            email:      'nbroxap4@hubpages.com',
        },
        {
            username:   'egameson5',
            password:   'hkTrYCR2K6L3',
            first_name: 'Ester',
            last_name:  'Gameson',
            role:       'Research Assistant II',
            email:      'egameson5@engadget.com',
        },
        {
            username:   'sclausen6',
            password:   'wt6sVWHKT1',
            first_name: 'Sada',
            last_name:  'Clausen',
            role:       'General Manager',
            email:      'sclausen6@hp.com',
        },
        {
            username:   'sspellessy7',
            password:   'j5BTAK',
            first_name: 'Sally',
            last_name:  'Spellessy',
            role:       'Automation Specialist I',
            email:      'sspellessy7@nba.com',
        },
        {
            username:   'bgallymore8',
            password:   'PpUrmzCmg5O1',
            first_name: 'Barbabra',
            last_name:  'Gallymore',
            role:       'Dental Hygienist',
            email:      'bgallymore8@fda.gov',
        },
        {
            username:   'broylance9',
            password:   'Rdjgy6',
            first_name: 'Bobbee',
            last_name:  'Roylance',
            role:       'Account Representative IV',
            email:      'broylance9@about.com',
        },
        {
            username:   'gjocica',
            password:   'VwtiXWyFEm',
            first_name: 'Germayne',
            last_name:  'Jocic',
            role:       'Assistant Media Planner',
            email:      'gjocica@odnoklassniki.ru',
        },
        {
            username:   'slorenzettob',
            password:   'G8wxxrtDn0Q',
            first_name: 'Sheila',
            last_name:  'Lorenzetto',
            role:       'VP Sales',
            email:      'slorenzettob@prweb.com',
        },
        {
            username:   'dstearnc',
            password:   'FXykERsT',
            first_name: 'Dru',
            last_name:  'Stearn',
            role:       'Teacher',
            email:      'dstearnc@exblog.jp',
        },
        {
            username:   'cdillowd',
            password:   '4IMKYgbi4',
            first_name: 'Clari',
            last_name:  'Dillow',
            role:       'Computer Systems Analyst II',
            email:      'cdillowd@miitbeian.gov.cn',
        },
        {
            username:   'cmerchante',
            password:   'D8nwrx6kPhe',
            first_name: 'Chrysa',
            last_name:  'Merchant',
            role:       'Programmer III',
            email:      'cmerchante@histats.com',
        },
        {
            username:   'mmcnernf',
            password:   'SujT9vx4A6',
            first_name: 'Melosa',
            last_name:  'McNern',
            role:       'Project Manager',
            email:      'mmcnernf@wsj.com',
        },
        {
            username:   'tzapaterog',
            password:   'tcGOrzhrO',
            first_name: 'Tiphani',
            last_name:  'Zapatero',
            role:       'General Manager',
            email:      'tzapaterog@shinystat.com',
        },
        {
            username:   'gcucinottah',
            password:   'QQphrMOB6V9O',
            first_name: 'Gonzales',
            last_name:  'Cucinotta',
            role:       'Chemical Engineer',
            email:      'gcucinottah@pagesperso-orange.fr',
        },
        {
            username:   'mcamelini',
            password:   '84qQxg',
            first_name: 'Meaghan',
            last_name:  'Camelin',
            role:       'Engineer I',
            email:      'mcamelini@statcounter.com',
        },
        {
            username:   'kroostanj',
            password:   'z0K2PSP',
            first_name: 'Kat',
            last_name:  'Roostan',
            role:       'Programmer III',
            email:      'kroostanj@oakley.com',
        },
        {
            username:   'ujiracekk',
            password:   '6lbYNHeS',
            first_name: 'Uriah',
            last_name:  'Jiracek',
            role:       'Product Engineer',
            email:      'ujiracekk@hc360.com',
        },
        {
            username:   'zvaiseyl',
            password:   '6llpmlrkvI6v',
            first_name: 'Zaneta',
            last_name:  'Vaisey',
            role:       'Editor',
            email:      'zvaiseyl@sun.com',
        },
        {
            username:   'hrimourm',
            password:   'KIRs2BIV',
            first_name: 'Hector',
            last_name:  'Rimour',
            role:       'VP Product Management',
            email:      'hrimourm@acquirethisname.com',
        },
        {
            username:   'amasin',
            password:   'dJ277aN',
            first_name: 'Araldo',
            last_name:  'Masi',
            role:       'Research Nurse',
            email:      'amasin@miitbeian.gov.cn',
        },
        {
            username:   'fnorketto',
            password:   'v2ty5c8q6',
            first_name: 'Frasquito',
            last_name:  'Norkett',
            role:       'Accountant IV',
            email:      'fnorketto@bluehost.com',
        },
        {
            username:   'jsaddp',
            password:   'mtX0CYm5Q1FE',
            first_name: 'Janek',
            last_name:  'Sadd',
            role:       'Help Desk Operator',
            email:      'jsaddp@bandcamp.com',
        },
        {
            username:   'emuselliq',
            password:   'I2vsvg',
            first_name: 'Ebba',
            last_name:  'Muselli',
            role:       'Paralegal',
            email:      'emuselliq@abc.net.au',
        },
        {
            username:   'egrundellr',
            password:   'hnbUwYSdp',
            first_name: 'Elka',
            last_name:  'Grundell',
            role:       'Mechanical Systems Engineer',
            email:      'egrundellr@tripadvisor.com',
        },
        {
            username:   'smees',
            password:   '7r73iet0',
            first_name: 'Sharai',
            last_name:  'Mee',
            role:       'Director of Sales',
            email:      'smees@dailymotion.com',
        },
        {
            username:   'surpetht',
            password:   'u6vITEv',
            first_name: 'Sharon',
            last_name:  'Urpeth',
            role:       'Research Nurse',
            email:      'surpetht@nytimes.com',
        },
        {
            username:   'odurdyu',
            password:   'Gb6n5vq',
            first_name: 'Orson',
            last_name:  'Durdy',
            role:       'Database Administrator I',
            email:      'odurdyu@netlog.com',
        },
        {
            username:   'edemangev',
            password:   'epizRtvCSlg',
            first_name: 'Elga',
            last_name:  'Demange',
            role:       'Assistant Manager',
            email:      'edemangev@craigslist.org',
        },
        {
            username:   'shurdisw',
            password:   '76LEexMS',
            first_name: 'Sergeant',
            last_name:  'Hurdis',
            role:       'Speech Pathologist',
            email:      'shurdisw@economist.com',
        },
        {
            username:   'jcrockattx',
            password:   '0xkIi3',
            first_name: 'Jethro',
            last_name:  'Crockatt',
            role:       'Design Engineer',
            email:      'jcrockattx@posterous.com',
        },
        {
            username:   'rdubsy',
            password:   'sgguPuHVn',
            first_name: 'Renato',
            last_name:  'Dubs',
            role:       'Civil Engineer',
            email:      'rdubsy@eepurl.com',
        },
        {
            username:   'smoppettz',
            password:   'By9I0Obunx2S',
            first_name: 'Salomo',
            last_name:  'Moppett',
            role:       'Physical Therapy Assistant',
            email:      'smoppettz@bandcamp.com',
        },
        {
            username:   'rgimber10',
            password:   'hJ5CNQ',
            first_name: 'Reinwald',
            last_name:  'Gimber',
            role:       'Human Resources Assistant I',
            email:      'rgimber10@wikimedia.org',
        },
        {
            username:   'lkale11',
            password:   'EtNsjRos4U5',
            first_name: 'Lavinia',
            last_name:  'Kale',
            role:       'Developer IV',
            email:      'lkale11@yale.edu',
        },
        {
            username:   'ubeachem12',
            password:   '1PnRthhF',
            first_name: 'Umeko',
            last_name:  'Beachem',
            role:       'Structural Analysis Engineer',
            email:      'ubeachem12@usgs.gov',
        },
        {
            username:   'fboxen13',
            password:   '6H1VIySG7T',
            first_name: 'Feliza',
            last_name:  'Boxen',
            role:       'Developer IV',
            email:      'fboxen13@so-net.ne.jp',
        },
        {
            username:   'imccloy14',
            password:   'U3G9zZyOnsJ',
            first_name: 'Indira',
            last_name:  'McCloy',
            role:       'GIS Technical Architect',
            email:      'imccloy14@creativecommons.org',
        },
        {
            username:   'churlestone15',
            password:   'oXZDqF',
            first_name: 'Christan',
            last_name:  'Hurlestone',
            role:       'Legal Assistant',
            email:      'churlestone15@technorati.com',
        },
        {
            username:   'ekenningham16',
            password:   'FOfJ9nA9n',
            first_name: 'Elmira',
            last_name:  'Kenningham',
            role:       'Compensation Analyst',
            email:      'ekenningham16@clickbank.net',
        },
        {
            username:   'ttremonte17',
            password:   'cN2jna0pxPc',
            first_name: 'Tabatha',
            last_name:  'Tremonte',
            role:       'Compensation Analyst',
            email:      'ttremonte17@about.com',
        },
        {
            username:   'nyakuntzov18',
            password:   '4f2sK4rEaZq',
            first_name: 'Nicholle',
            last_name:  'Yakuntzov',
            role:       'Business Systems Development Analyst',
            email:      'nyakuntzov18@theguardian.com',
        },
        {
            username:   'wvelareal19',
            password:   '1629WFRG52SL',
            first_name: 'Waverly',
            last_name:  'Velareal',
            role:       'Help Desk Technician',
            email:      'wvelareal19@icq.com',
        },
        {
            username:   'tberick1a',
            password:   'qL2TRSfPy1',
            first_name: 'Timmie',
            last_name:  'Berick',
            role:       'VP Sales',
            email:      'tberick1a@pagesperso-orange.fr',
        },
        {
            username:   'meustice1b',
            password:   'd8CmhuQwy7j',
            first_name: 'Maxie',
            last_name:  'Eustice',
            role:       'Geological Engineer',
            email:      'meustice1b@illinois.edu',
        },
        {
            username:   'ghewlings1c',
            password:   '25Kh65',
            first_name: 'Gideon',
            last_name:  'Hewlings',
            role:       'Design Engineer',
            email:      'ghewlings1c@dailymotion.com',
        },
        {
            username:   'ujackett1d',
            password:   'T5ccq73ET',
            first_name: 'Ulysses',
            last_name:  'Jackett',
            role:       'Internal Auditor',
            email:      'ujackett1d@yandex.ru',
        },
        {
            username:   'challgate1e',
            password:   'Y46zQhX3doK',
            first_name: 'Corabel',
            last_name:  'Hallgate',
            role:       'Information Systems Manager',
            email:      'challgate1e@hud.gov',
        },
        {
            username:   'esimoes1f',
            password:   'waEH7oSF',
            first_name: 'Elliot',
            last_name:  'Simoes',
            role:       'Editor',
            email:      'esimoes1f@csmonitor.com',
        },
        {
            username:   'agudd1g',
            password:   'SLokNOp7zyp',
            first_name: 'Addison',
            last_name:  'Gudd',
            role:       'Budget/Accounting Analyst I',
            email:      'agudd1g@cbc.ca',
        },
        {
            username:   'mdulton1h',
            password:   'HpR6QOYYlUmo',
            first_name: 'Mellisent',
            last_name:  'Dulton',
            role:       'Quality Engineer',
            email:      'mdulton1h@wunderground.com',
        },
        {
            username:   'trenish1i',
            password:   'dhIAnprNKi',
            first_name: 'Talbot',
            last_name:  'Renish',
            role:       'Social Worker',
            email:      'trenish1i@trellian.com',
        },
        {
            username:   'pinold1j',
            password:   '64aRZFW',
            first_name: 'Pace',
            last_name:  'Inold',
            role:       'Mechanical Systems Engineer',
            email:      'pinold1j@reuters.com',
        },
        {
            username:   'rjago1k',
            password:   'sofzQc',
            first_name: 'Rutger',
            last_name:  'Jago',
            role:       'Tax Accountant',
            email:      'rjago1k@ocn.ne.jp',
        },
        {
            username:   'hvedeniktov1l',
            password:   'AmnPMXo',
            first_name: 'Heddi',
            last_name:  'Vedeniktov',
            role:       'GIS Technical Architect',
            email:      'hvedeniktov1l@washington.edu',
        },
        {
            username:   'acalam1m',
            password:   'QhJhvDB',
            first_name: 'Agnese',
            last_name:  'Calam',
            role:       'Statistician III',
            email:      'acalam1m@discovery.com',
        },
        {
            username:   'mfernanando1n',
            password:   'GxZIQQr8qD',
            first_name: 'Marianna',
            last_name:  'Fernanando',
            role:       'Human Resources Assistant II',
            email:      'mfernanando1n@live.com',
        },
        {
            username:   'gswatman1o',
            password:   '9Yep295a',
            first_name: 'Gus',
            last_name:  'Swatman',
            role:       'Assistant Professor',
            email:      'gswatman1o@infoseek.co.jp',
        },
        {
            username:   'jskingle1p',
            password:   'EqyAcoCj',
            first_name: 'Jacklin',
            last_name:  'Skingle',
            role:       'Dental Hygienist',
            email:      'jskingle1p@yale.edu',
        },
        {
            username:   'vlarwell1q',
            password:   '4yXyXMsG',
            first_name: 'Vivi',
            last_name:  'Larwell',
            role:       'Nuclear Power Engineer',
            email:      'vlarwell1q@fda.gov',
        },
        {
            username:   'cgodrich1r',
            password:   'jKkeTJJ0q',
            first_name: 'Carleton',
            last_name:  'Godrich',
            role:       'Office Assistant II',
            email:      'cgodrich1r@cornell.edu',
        },
        {
            username:   'cskey1s',
            password:   'LBH1u0M',
            first_name: 'Cristobal',
            last_name:  'Skey',
            role:       'Director of Sales',
            email:      'cskey1s@instagram.com',
        },
        {
            username:   'cclaypool1t',
            password:   '5A11kdYAAs',
            first_name: 'Carmencita',
            last_name:  'Claypool',
            role:       'Web Designer III',
            email:      'cclaypool1t@blogs.com',
        },
        {
            username:   'kgonzalo1u',
            password:   '91Vj5Usn',
            first_name: 'Kissiah',
            last_name:  'Gonzalo',
            role:       'Assistant Media Planner',
            email:      'kgonzalo1u@weebly.com',
        },
        {
            username:   'jcantero1v',
            password:   'Wfv6t5De',
            first_name: 'Jacintha',
            last_name:  'Cantero',
            role:       'Graphic Designer',
            email:      'jcantero1v@java.com',
        },
        {
            username:   'awank1w',
            password:   'Iy5eHjMQacI',
            first_name: 'Andros',
            last_name:  'Wank',
            role:       'Human Resources Assistant II',
            email:      'awank1w@blogger.com',
        },
        {
            username:   'egagin1x',
            password:   'jGRrCc',
            first_name: 'Erna',
            last_name:  'Gagin',
            role:       'Recruiter',
            email:      'egagin1x@amazonaws.com',
        },
        {
            username:   'wvallerine1y',
            password:   'DEc7Wx9o',
            first_name: 'Wilhelm',
            last_name:  'Vallerine',
            role:       'Teacher',
            email:      'wvallerine1y@epa.gov',
        },
        {
            username:   'ggaddas1z',
            password:   'skdBHJeF04',
            first_name: 'Goddard',
            last_name:  'Gaddas',
            role:       'Design Engineer',
            email:      'ggaddas1z@stanford.edu',
        },
        {
            username:   'dpadgham20',
            password:   'agBoOC2pWOj',
            first_name: 'Doralynne',
            last_name:  'Padgham',
            role:       'Structural Analysis Engineer',
            email:      'dpadgham20@imgur.com',
        },
        {
            username:   'mwilsee21',
            password:   'Ij2sbv2pdb7',
            first_name: 'Michell',
            last_name:  'Wilsee',
            role:       'Systems Administrator III',
            email:      'mwilsee21@examiner.com',
        },
        {
            username:   'keller22',
            password:   'JWAMLG7F0',
            first_name: 'Kandace',
            last_name:  'Eller',
            role:       'Occupational Therapist',
            email:      'keller22@usatoday.com',
        },
        {
            username:   'malmeida23',
            password:   'bpYpL0zkD',
            first_name: 'Morena',
            last_name:  'Almeida',
            role:       'Account Executive',
            email:      'malmeida23@newyorker.com',
        },
        {
            username:   'scrowest24',
            password:   '4c7Fy8N0r8',
            first_name: 'Sonnie',
            last_name:  'Crowest',
            role:       'Senior Quality Engineer',
            email:      'scrowest24@salon.com',
        },
        {
            username:   'mreeves25',
            password:   'X2D5bTA3o',
            first_name: 'Merci',
            last_name:  'Reeves',
            role:       'Automation Specialist III',
            email:      'mreeves25@jigsy.com',
        },
        {
            username:   'gsailer26',
            password:   'EiZb79ZKYsK',
            first_name: 'Gunner',
            last_name:  'Sailer',
            role:       'Financial Analyst',
            email:      'gsailer26@si.edu',
        },
        {
            username:   'bmitro27',
            password:   '672cl9wsd',
            first_name: 'Breena',
            last_name:  'Mitro',
            role:       'Financial Analyst',
            email:      'bmitro27@globo.com',
        },
        {
            username:   'rohingerty28',
            password:   'x8v3aHl',
            first_name: 'Raimundo',
            last_name:  'O\'Hingerty',
            role:       'Assistant Professor',
            email:      'rohingerty28@yale.edu',
        },
        {
            username:   'ldonati29',
            password:   'e1LeEfnn34n',
            first_name: 'Lorrie',
            last_name:  'Donati',
            role:       'Account Representative II',
            email:      'ldonati29@umich.edu',
        },
        {
            username:   'evereker2a',
            password:   'nFzbdb0fm5S',
            first_name: 'Estrellita',
            last_name:  'Vereker',
            role:       'Financial Analyst',
            email:      'evereker2a@scientificamerican.com',
        },
        {
            username:   'ckulas2b',
            password:   'tn45uZSa1HE0',
            first_name: 'Claudius',
            last_name:  'Kulas',
            role:       'Assistant Manager',
            email:      'ckulas2b@wikimedia.org',
        },
        {
            username:   'kgordge2c',
            password:   '2JMfyYLZcRSE',
            first_name: 'Kimberly',
            last_name:  'Gordge',
            role:       'Senior Quality Engineer',
            email:      'kgordge2c@cbc.ca',
        },
        {
            username:   'khirche2d',
            password:   'j74Kt1So',
            first_name: 'Kendall',
            last_name:  'Hirche',
            role:       'Occupational Therapist',
            email:      'khirche2d@unblog.fr',
        },
        {
            username:   'swolfinger2e',
            password:   '7AEjjbZxV',
            first_name: 'Sawyer',
            last_name:  'Wolfinger',
            role:       'Human Resources Assistant II',
            email:      'swolfinger2e@bbc.co.uk',
        },
        {
            username:   'kgutans2f',
            password:   'JN6KvuU5j',
            first_name: 'Kylie',
            last_name:  'Gutans',
            role:       'Accountant II',
            email:      'kgutans2f@merriam-webster.com',
        },
        {
            username:   'sjuanes2g',
            password:   'Rk2eLUeIC',
            first_name: 'Sarene',
            last_name:  'Juanes',
            role:       'Executive Secretary',
            email:      'sjuanes2g@marketwatch.com',
        },
        {
            username:   'smapstone2h',
            password:   'GuhRXu',
            first_name: 'Stacy',
            last_name:  'Mapstone',
            role:       'Dental Hygienist',
            email:      'smapstone2h@exblog.jp',
        },
        {
            username:   'mkesley2i',
            password:   'C4TRg46Q',
            first_name: 'Mallory',
            last_name:  'Kesley',
            role:       'Budget/Accounting Analyst II',
            email:      'mkesley2i@seattletimes.com',
        },
        {
            username:   'idutch2j',
            password:   'fkVxAil',
            first_name: 'Iolanthe',
            last_name:  'Dutch',
            role:       'Teacher',
            email:      'idutch2j@oracle.com',
        },
        {
            username:   'eseville2k',
            password:   'UhIjOjvE7',
            first_name: 'Erena',
            last_name:  'Seville',
            role:       'Sales Associate',
            email:      'eseville2k@oakley.com',
        },
        {
            username:   'kzotto2l',
            password:   'NZHyxxmjTwrg',
            first_name: 'Korie',
            last_name:  'Zotto',
            role:       'Junior Executive',
            email:      'kzotto2l@desdev.cn',
        },
        {
            username:   'sayerst2m',
            password:   'hkqShEPud0',
            first_name: 'Standford',
            last_name:  'Ayerst',
            role:       'Physical Therapy Assistant',
            email:      'sayerst2m@harvard.edu',
        },
        {
            username:   'cdysart2n',
            password:   'LS5V0Y4a',
            first_name: 'Clare',
            last_name:  'Dysart',
            role:       'Research Assistant II',
            email:      'cdysart2n@cnbc.com',
        },
        {
            username:   'ahaet2o',
            password:   'tnrsYOyiPQ',
            first_name: 'Axe',
            last_name:  'Haet',
            role:       'Desktop Support Technician',
            email:      'ahaet2o@163.com',
        },
        {
            username:   'gmackrill2p',
            password:   'yPu4YaoRn5o',
            first_name: 'Garner',
            last_name:  'Mackrill',
            role:       'Director of Sales',
            email:      'gmackrill2p@miibeian.gov.cn',
        },
        {
            username:   'lkerrane2q',
            password:   '2JBCZCB5hKoN',
            first_name: 'Lisle',
            last_name:  'Kerrane',
            role:       'Administrative Officer',
            email:      'lkerrane2q@blogspot.com',
        },
        {
            username:   'rclemmens2r',
            password:   'BCG4Qa3RzM',
            first_name: 'Reeva',
            last_name:  'Clemmens',
            role:       'Nurse Practicioner',
            email:      'rclemmens2r@fastcompany.com',
        },
        {
            username:   'ddamiata2s',
            password:   'WsCjXs',
            first_name: 'Delphinia',
            last_name:  'Damiata',
            role:       'VP Accounting',
            email:      'ddamiata2s@example.com',
        },
        {
            username:   'kdunniom2t',
            password:   '2IPNMKvv5in2',
            first_name: 'Keely',
            last_name:  'Dunniom',
            role:       'Analyst Programmer',
            email:      'kdunniom2t@over-blog.com',
        },
        {
            username:   'bfrie2u',
            password:   '6rna77UXS',
            first_name: 'Bradley',
            last_name:  'Frie',
            role:       'Recruiter',
            email:      'bfrie2u@t.co',
        },
        {
            username:   'avanderveldt2v',
            password:   '4b1WypE',
            first_name: 'Annalise',
            last_name:  'Van der Veldt',
            role:       'Chief Design Engineer',
            email:      'avanderveldt2v@reddit.com',
        },
        {
            username:   'dattac2w',
            password:   'gN47qYjKk',
            first_name: 'Danella',
            last_name:  'Attac',
            role:       'Assistant Professor',
            email:      'dattac2w@reuters.com',
        },
        {
            username:   'amcavinchey2x',
            password:   'KjYY4MC3',
            first_name: 'Adelina',
            last_name:  'McAvinchey',
            role:       'Information Systems Manager',
            email:      'amcavinchey2x@about.com',
        },
        {
            username:   'htilzey2y',
            password:   'BBPiiTqbvgk',
            first_name: 'Hildagard',
            last_name:  'Tilzey',
            role:       'Web Designer III',
            email:      'htilzey2y@barnesandnoble.com',
        },
        {
            username:   'ajahn2z',
            password:   '2QQyPGYVR17',
            first_name: 'Allistir',
            last_name:  'Jahn',
            role:       'Registered Nurse',
            email:      'ajahn2z@blinklist.com',
        },
        {
            username:   'chollows30',
            password:   'ZXRKNHC2bp4',
            first_name: 'Clark',
            last_name:  'Hollows',
            role:       'Recruiter',
            email:      'chollows30@free.fr',
        },
        {
            username:   'otweddle31',
            password:   'WsQbIQKR',
            first_name: 'Orion',
            last_name:  'Tweddle',
            role:       'Assistant Media Planner',
            email:      'otweddle31@friendfeed.com',
        },
        {
            username:   'rspring32',
            password:   'DvCJAuhFO7W',
            first_name: 'Robby',
            last_name:  'Spring',
            role:       'Structural Analysis Engineer',
            email:      'rspring32@businessinsider.com',
        },
        {
            username:   'jcicetti33',
            password:   'fcZcfK03jmI',
            first_name: 'Jessika',
            last_name:  'Cicetti',
            role:       'Financial Analyst',
            email:      'jcicetti33@sfgate.com',
        },
        {
            username:   'jsinton34',
            password:   'TmpOjPT',
            first_name: 'Jackie',
            last_name:  'Sinton',
            role:       'Administrative Officer',
            email:      'jsinton34@sogou.com',
        },
        {
            username:   'jdalliston35',
            password:   't97N3c',
            first_name: 'Jase',
            last_name:  'Dalliston',
            role:       'GIS Technical Architect',
            email:      'jdalliston35@rambler.ru',
        },
        {
            username:   'gespadater36',
            password:   'szWOOHygDnC',
            first_name: 'Guinevere',
            last_name:  'Espadater',
            role:       'Legal Assistant',
            email:      'gespadater36@yandex.ru',
        },
        {
            username:   'yryce37',
            password:   '3Q813evwq',
            first_name: 'Yvor',
            last_name:  'Ryce',
            role:       'Software Consultant',
            email:      'yryce37@dmoz.org',
        },
        {
            username:   'ginchbald38',
            password:   'GA6piql',
            first_name: 'Giff',
            last_name:  'Inchbald',
            role:       'VP Product Management',
            email:      'ginchbald38@fotki.com',
        },
        {
            username:   'sdonkersley39',
            password:   'lXlFHCEytA',
            first_name: 'Sophronia',
            last_name:  'Donkersley',
            role:       'Sales Representative',
            email:      'sdonkersley39@fc2.com',
        },
        {
            username:   'candren3a',
            password:   'tT5DZp',
            first_name: 'Cherish',
            last_name:  'Andren',
            role:       'Geological Engineer',
            email:      'candren3a@scientificamerican.com',
        },
        {
            username:   'vpimblotte3b',
            password:   'vDRcB2LCgpam',
            first_name: 'Verge',
            last_name:  'Pimblotte',
            role:       'Web Designer IV',
            email:      'vpimblotte3b@jiathis.com',
        },
        {
            username:   'bnanninini3c',
            password:   'ZGyJB7WqUyg',
            first_name: 'Bert',
            last_name:  'Nanninini',
            role:       'Recruiter',
            email:      'bnanninini3c@dell.com',
        },
        {
            username:   'jbraxton3d',
            password:   'ZIw7L7CCk',
            first_name: 'Janna',
            last_name:  'Braxton',
            role:       'Nurse Practicioner',
            email:      'jbraxton3d@china.com.cn',
        },
        {
            username:   'eeastman3e',
            password:   '7uQAZfpf',
            first_name: 'Eugenio',
            last_name:  'Eastman',
            role:       'Sales Representative',
            email:      'eeastman3e@discuz.net',
        },
        {
            username:   'ieller3f',
            password:   'bXtxiA5QY',
            first_name: 'Ingaborg',
            last_name:  'Eller',
            role:       'VP Marketing',
            email:      'ieller3f@zimbio.com',
        },
        {
            username:   'sabrahamoff3g',
            password:   'lrj31toF4oM',
            first_name: 'Sayre',
            last_name:  'Abrahamoff',
            role:       'Information Systems Manager',
            email:      'sabrahamoff3g@reverbnation.com',
        },
        {
            username:   'glofts3h',
            password:   'aibN1WbGO',
            first_name: 'Graehme',
            last_name:  'Lofts',
            role:       'Design Engineer',
            email:      'glofts3h@usatoday.com',
        },
        {
            username:   'bmilmore3i',
            password:   'v3bDC9qoHjEo',
            first_name: 'Beverlie',
            last_name:  'Milmore',
            role:       'Office Assistant I',
            email:      'bmilmore3i@networkadvertising.org',
        },
        {
            username:   'tnoli3j',
            password:   'T3zGSQjqgB7q',
            first_name: 'Toma',
            last_name:  'Noli',
            role:       'VP Accounting',
            email:      'tnoli3j@cnbc.com',
        },
        {
            username:   'cvowden3k',
            password:   'NEPgSF',
            first_name: 'Cicily',
            last_name:  'Vowden',
            role:       'Associate Professor',
            email:      'cvowden3k@prlog.org',
        },
        {
            username:   'pmilnthorpe3l',
            password:   'nD1eQqpq4LC',
            first_name: 'Petr',
            last_name:  'Milnthorpe',
            role:       'Human Resources Manager',
            email:      'pmilnthorpe3l@foxnews.com',
        },
        {
            username:   'hyuryaev3m',
            password:   'KiwQLSRL',
            first_name: 'Hector',
            last_name:  'Yuryaev',
            role:       'Human Resources Manager',
            email:      'hyuryaev3m@ebay.com',
        },
        {
            username:   'esprowle3n',
            password:   'rrCbXoSWr200',
            first_name: 'Euphemia',
            last_name:  'Sprowle',
            role:       'Nurse Practicioner',
            email:      'esprowle3n@msn.com',
        },
        {
            username:   'cboxill3o',
            password:   'tvToms',
            first_name: 'Corbett',
            last_name:  'Boxill',
            role:       'Senior Financial Analyst',
            email:      'cboxill3o@house.gov',
        },
        {
            username:   'ciston3p',
            password:   'KyMC0YAXr8',
            first_name: 'Coraline',
            last_name:  'Iston',
            role:       'Chief Design Engineer',
            email:      'ciston3p@homestead.com',
        },
        {
            username:   'hdecullip3q',
            password:   '1MQZhBGGco',
            first_name: 'Hazel',
            last_name:  'de Cullip',
            role:       'Tax Accountant',
            email:      'hdecullip3q@bing.com',
        },
        {
            username:   'mwitheford3r',
            password:   'PQwBDg',
            first_name: 'Matt',
            last_name:  'Witheford',
            role:       'Sales Representative',
            email:      'mwitheford3r@timesonline.co.uk',
        },
        {
            username:   'jaloshkin3s',
            password:   'GUrlsb',
            first_name: 'Jill',
            last_name:  'Aloshkin',
            role:       'Speech Pathologist',
            email:      'jaloshkin3s@house.gov',
        },
        {
            username:   'rflawith3t',
            password:   'lgzRM9lw0py',
            first_name: 'Ruthe',
            last_name:  'Flawith',
            role:       'Help Desk Technician',
            email:      'rflawith3t@upenn.edu',
        },
        {
            username:   'gbernaldo3u',
            password:   'BTxnanpfXdua',
            first_name: 'Gay',
            last_name:  'Bernaldo',
            role:       'Desktop Support Technician',
            email:      'gbernaldo3u@google.com.br',
        },
        {
            username:   'laslott3v',
            password:   'VoTiGufEeK',
            first_name: 'Lyman',
            last_name:  'Aslott',
            role:       'Systems Administrator I',
            email:      'laslott3v@smh.com.au',
        },
        {
            username:   'pbrash3w',
            password:   'NoSrtsB',
            first_name: 'Patty',
            last_name:  'Brash',
            role:       'Systems Administrator II',
            email:      'pbrash3w@shinystat.com',
        },
        {
            username:   'krollingson3x',
            password:   'aTs4KNzrtgE',
            first_name: 'Kerrill',
            last_name:  'Rollingson',
            role:       'Teacher',
            email:      'krollingson3x@amazon.de',
        },
        {
            username:   'dhoundsom3y',
            password:   'k2xdR41JHp',
            first_name: 'Deloria',
            last_name:  'Houndsom',
            role:       'Geological Engineer',
            email:      'dhoundsom3y@arizona.edu',
        },
        {
            username:   'ukoppke3z',
            password:   'idX7qfFkk7Ns',
            first_name: 'Uta',
            last_name:  'Koppke',
            role:       'Research Nurse',
            email:      'ukoppke3z@businessweek.com',
        },
        {
            username:   'sburchard40',
            password:   'usuOw0ZjUAG',
            first_name: 'Sibley',
            last_name:  'Burchard',
            role:       'Editor',
            email:      'sburchard40@army.mil',
        },
        {
            username:   'kmansion41',
            password:   'DAidwa',
            first_name: 'Kimball',
            last_name:  'Mansion',
            role:       'Project Manager',
            email:      'kmansion41@hugedomains.com',
        },
        {
            username:   'rmansour42',
            password:   'SmZ2g4AEM7u',
            first_name: 'Rosalind',
            last_name:  'Mansour',
            role:       'Mechanical Systems Engineer',
            email:      'rmansour42@bluehost.com',
        },
        {
            username:   'gsim43',
            password:   'OAjqBQILvU',
            first_name: 'Gusty',
            last_name:  'Sim',
            role:       'Safety Technician II',
            email:      'gsim43@shareasale.com',
        },
        {
            username:   'hgirardengo44',
            password:   'Ik08gA6m',
            first_name: 'Hewie',
            last_name:  'Girardengo',
            role:       'Research Nurse',
            email:      'hgirardengo44@w3.org',
        },
        {
            username:   'rcourson45',
            password:   'cUtilNkYQrIO',
            first_name: 'Robinette',
            last_name:  'Courson',
            role:       'Payment Adjustment Coordinator',
            email:      'rcourson45@infoseek.co.jp',
        },
        {
            username:   'awetton46',
            password:   'Z1NPIZ0PB8',
            first_name: 'Alaric',
            last_name:  'Wetton',
            role:       'Developer III',
            email:      'awetton46@ucoz.ru',
        },
        {
            username:   'hmeryett47',
            password:   'AhspFwSvq',
            first_name: 'Hali',
            last_name:  'Meryett',
            role:       'Sales Associate',
            email:      'hmeryett47@usnews.com',
        },
        {
            username:   'elittell48',
            password:   'yvGuPUJV5G',
            first_name: 'Ella',
            last_name:  'Littell',
            role:       'Electrical Engineer',
            email:      'elittell48@rambler.ru',
        },
        {
            username:   'lpocklington49',
            password:   'Qwr6vgY',
            first_name: 'Latia',
            last_name:  'Pocklington',
            role:       'Technical Writer',
            email:      'lpocklington49@linkedin.com',
        },
        {
            username:   'fwildber4a',
            password:   'HAMCplQYQV',
            first_name: 'Franni',
            last_name:  'Wildber',
            role:       'Programmer I',
            email:      'fwildber4a@google.fr',
        },
        {
            username:   'blilly4b',
            password:   'CL8gmmY',
            first_name: 'Birdie',
            last_name:  'Lilly',
            role:       'Human Resources Assistant II',
            email:      'blilly4b@nsw.gov.au',
        },
        {
            username:   'rarson4c',
            password:   'LV8I8nnjj',
            first_name: 'Rubi',
            last_name:  'Arson',
            role:       'Human Resources Manager',
            email:      'rarson4c@admin.ch',
        },
        {
            username:   'ghollows4d',
            password:   'Vger2TwcCg',
            first_name: 'Galina',
            last_name:  'Hollows',
            role:       'Registered Nurse',
            email:      'ghollows4d@dell.com',
        },
        {
            username:   'rkneaphsey4e',
            password:   'cKsAFMm',
            first_name: 'Reider',
            last_name:  'Kneaphsey',
            role:       'Data Coordiator',
            email:      'rkneaphsey4e@china.com.cn',
        },
        {
            username:   'irawle4f',
            password:   'P8iVRgJdi',
            first_name: 'Ibrahim',
            last_name:  'Rawle',
            role:       'Operator',
            email:      'irawle4f@seesaa.net',
        },
        {
            username:   'lwigin4g',
            password:   'POfKowl',
            first_name: 'Luz',
            last_name:  'Wigin',
            role:       'Legal Assistant',
            email:      'lwigin4g@multiply.com',
        },
        {
            username:   'sdalzell4h',
            password:   'TU4V9zJ3',
            first_name: 'Sarge',
            last_name:  'Dalzell',
            role:       'Nurse Practicioner',
            email:      'sdalzell4h@msn.com',
        },
        {
            username:   'moneal4i',
            password:   'UGwlhE6NWJ',
            first_name: 'Maynord',
            last_name:  'Oneal',
            role:       'VP Accounting',
            email:      'moneal4i@ebay.com',
        },
        {
            username:   'dgillings4j',
            password:   'ZVaeEs',
            first_name: 'Denna',
            last_name:  'Gillings',
            role:       'Web Developer I',
            email:      'dgillings4j@twitpic.com',
        },
        {
            username:   'athebe4k',
            password:   'wm402HmS',
            first_name: 'Angie',
            last_name:  'Thebe',
            role:       'Cost Accountant',
            email:      'athebe4k@alexa.com',
        },
        {
            username:   'syesenin4l',
            password:   'R3KBfFr',
            first_name: 'Sara-ann',
            last_name:  'Yesenin',
            role:       'Pharmacist',
            email:      'syesenin4l@sina.com.cn',
        },
        {
            username:   'mcourtonne4m',
            password:   'QEULTlfFUoP',
            first_name: 'Marley',
            last_name:  'Courtonne',
            role:       'Geologist IV',
            email:      'mcourtonne4m@indiegogo.com',
        },
        {
            username:   'bheskey4n',
            password:   'KMwpV2NPVFMk',
            first_name: 'Beulah',
            last_name:  'Heskey',
            role:       'Computer Systems Analyst IV',
            email:      'bheskey4n@google.com',
        },
        {
            username:   'rdangelo4o',
            password:   'DTwfoG7ft',
            first_name: 'Ranna',
            last_name:  'D\' Angelo',
            role:       'Project Manager',
            email:      'rdangelo4o@huffingtonpost.com',
        },
        {
            username:   'bvitte4p',
            password:   'zQCaJ6',
            first_name: 'Blane',
            last_name:  'Vitte',
            role:       'Assistant Manager',
            email:      'bvitte4p@ed.gov',
        },
        {
            username:   'awardhaw4q',
            password:   'XwAedNP',
            first_name: 'Ado',
            last_name:  'Wardhaw',
            role:       'Safety Technician II',
            email:      'awardhaw4q@networksolutions.com',
        },
        {
            username:   'tbauld4r',
            password:   'MU5M1s',
            first_name: 'Tandie',
            last_name:  'Bauld',
            role:       'Engineer II',
            email:      'tbauld4r@mail.ru',
        },
        {
            username:   'ccurd4s',
            password:   'tAhNyZZd1',
            first_name: 'Cheston',
            last_name:  'Curd',
            role:       'Social Worker',
            email:      'ccurd4s@china.com.cn',
        },
        {
            username:   'akasher4t',
            password:   '9mFEHxYPil7',
            first_name: 'Aarika',
            last_name:  'Kasher',
            role:       'Mechanical Systems Engineer',
            email:      'akasher4t@simplemachines.org',
        },
        {
            username:   'slycett4u',
            password:   'FYPkxAk',
            first_name: 'Shelden',
            last_name:  'Lycett',
            role:       'Help Desk Technician',
            email:      'slycett4u@imdb.com',
        },
        {
            username:   'bjimson4v',
            password:   'PYG07eOP',
            first_name: 'Berna',
            last_name:  'Jimson',
            role:       'Senior Cost Accountant',
            email:      'bjimson4v@uiuc.edu',
        },
        {
            username:   'tmccaughran4w',
            password:   'TWQ4kGRlZ0',
            first_name: 'Tildie',
            last_name:  'McCaughran',
            role:       'Assistant Manager',
            email:      'tmccaughran4w@facebook.com',
        },
        {
            username:   'jdiddams4x',
            password:   'Itq2e3a9',
            first_name: 'Janeen',
            last_name:  'Diddams',
            role:       'Payment Adjustment Coordinator',
            email:      'jdiddams4x@oaic.gov.au',
        },
        {
            username:   'ltessier4y',
            password:   'nqXA0Cl',
            first_name: 'Lloyd',
            last_name:  'Tessier',
            role:       'Database Administrator IV',
            email:      'ltessier4y@arstechnica.com',
        },
        {
            username:   'cmapson4z',
            password:   'gDCeYqzaE8Mh',
            first_name: 'Curtis',
            last_name:  'Mapson',
            role:       'Technical Writer',
            email:      'cmapson4z@psu.edu',
        },
        {
            username:   'dsymon50',
            password:   'wxKxwn',
            first_name: 'Donia',
            last_name:  'Symon',
            role:       'Research Associate',
            email:      'dsymon50@disqus.com',
        },
        {
            username:   'asiderfin51',
            password:   'H7m5xyGOvQ',
            first_name: 'Almeta',
            last_name:  'Siderfin',
            role:       'Account Representative I',
            email:      'asiderfin51@admin.ch',
        },
        {
            username:   'mtyrwhitt52',
            password:   '03VCGzG5JGy',
            first_name: 'Mareah',
            last_name:  'Tyrwhitt',
            role:       'Chemical Engineer',
            email:      'mtyrwhitt52@smugmug.com',
        },
        {
            username:   'vcarlyon53',
            password:   'YVXpVWogv',
            first_name: 'Vassily',
            last_name:  'Carlyon',
            role:       'Help Desk Technician',
            email:      'vcarlyon53@who.int',
        },
        {
            username:   'astonehewer54',
            password:   '7QKHHGEK',
            first_name: 'Abbie',
            last_name:  'Stonehewer',
            role:       'Product Engineer',
            email:      'astonehewer54@cdbaby.com',
        },
        {
            username:   'klammertz55',
            password:   'XCzo0ZkbM',
            first_name: 'Kenna',
            last_name:  'Lammertz',
            role:       'Accounting Assistant IV',
            email:      'klammertz55@alibaba.com',
        },
        {
            username:   'dchivers56',
            password:   'HFV26eE',
            first_name: 'Daphne',
            last_name:  'Chivers',
            role:       'Systems Administrator I',
            email:      'dchivers56@com.com',
        },
        {
            username:   'dmaccallester57',
            password:   'OHe2OKF',
            first_name: 'Doro',
            last_name:  'MacCallester',
            role:       'Cost Accountant',
            email:      'dmaccallester57@jugem.jp',
        },
        {
            username:   'rpharaoh58',
            password:   'S11kngkZc',
            first_name: 'Robenia',
            last_name:  'Pharaoh',
            role:       'Automation Specialist I',
            email:      'rpharaoh58@smh.com.au',
        },
        {
            username:   'hbalaizot59',
            password:   'ox7oCdw',
            first_name: 'Harrison',
            last_name:  'Balaizot',
            role:       'Assistant Professor',
            email:      'hbalaizot59@tmall.com',
        },
        {
            username:   'dmccomb5a',
            password:   'At0Hsumz3qU',
            first_name: 'Dasya',
            last_name:  'Mc Comb',
            role:       'Accountant III',
            email:      'dmccomb5a@berkeley.edu',
        },
        {
            username:   'wcosson5b',
            password:   'mgRbEC',
            first_name: 'Weber',
            last_name:  'Cosson',
            role:       'Software Consultant',
            email:      'wcosson5b@feedburner.com',
        },
        {
            username:   'ctoomey5c',
            password:   'nUM77B1jAA',
            first_name: 'Cornell',
            last_name:  'Toomey',
            role:       'Quality Engineer',
            email:      'ctoomey5c@bizjournals.com',
        },
        {
            username:   'bber5d',
            password:   '1434cy',
            first_name: 'Briano',
            last_name:  'Ber',
            role:       'Quality Control Specialist',
            email:      'bber5d@cocolog-nifty.com',
        },
        {
            username:   'bfaircley5e',
            password:   'AOYgLO6',
            first_name: 'Billy',
            last_name:  'Faircley',
            role:       'Software Consultant',
            email:      'bfaircley5e@hubpages.com',
        },
        {
            username:   'awoolrich5f',
            password:   '3a0vxdIJ',
            first_name: 'Angie',
            last_name:  'Woolrich',
            role:       'Community Outreach Specialist',
            email:      'awoolrich5f@domainmarket.com',
        },
        {
            username:   'hplaister5g',
            password:   'UInlPIbw',
            first_name: 'Huntlee',
            last_name:  'Plaister',
            role:       'Internal Auditor',
            email:      'hplaister5g@alexa.com',
        },
        {
            username:   'cstollenberg5h',
            password:   'eSFgMrmV',
            first_name: 'Cissy',
            last_name:  'Stollenberg',
            role:       'Occupational Therapist',
            email:      'cstollenberg5h@bbb.org',
        },
        {
            username:   'krosenstein5i',
            password:   '7f5kopB7Ft',
            first_name: 'Kelsy',
            last_name:  'Rosenstein',
            role:       'Environmental Specialist',
            email:      'krosenstein5i@twitter.com',
        },
        {
            username:   'ccurthoys5j',
            password:   'moIFYq',
            first_name: 'Catherine',
            last_name:  'Curthoys',
            role:       'Occupational Therapist',
            email:      'ccurthoys5j@elegantthemes.com',
        },
    ]
    console.log(users[0])

    for (var i = 0; i < users.length; i++) {

        user = new User(users[i])
        user.save()
            .then(item => {
                console.log('added user ' + user.username)
            })
            .catch(err => {
                console.log('Error adding user ' + user.username)
            })
    }

    res.render('reset', {title: 'Reset DB', message: 'Added ' + users.length + ' users.'})
})


defaultRoutes.route('/injection-tool').get(async (req, res) => {
    // let username = req.query.username;
    const url_lookup = req.query.url_lookup
    if (typeof url_lookup === 'undefined' || url_lookup == '') {
        res.render('injectionTool', {title: 'injectionTool', users: 0})
    } else {
        const list_of_optional_vulnerability = [
            '\' || \'a\'==\'a',
            '\'; \'a\'==\'a',
            'ghost',
        ]

        const list_of_legitc_values = [
            'ghost',
            'blabla bla',
        ]
        const url                   = url_lookup.split('?')[0]
        const parameters_names      = url_lookup.split('?')[1]
            .split('&')
            .map((parameter) => parameter.split('=')[0])

        let non_lig_paramaters = {}
        parameters_names.forEach((value) => {
            non_lig_paramaters[value] = list_of_optional_vulnerability[0]
        })

        let lig_paramaters = {}
        parameters_names.forEach((value) => {
            lig_paramaters[value] = list_of_legitc_values[0]
        })


        const percDiff = (A, B) => 100 * Math.abs((A - B) / ((A + B) / 2))


        let paramater_result = await parameters_names.map(async (url_param) => {

            let vulnerability_result = []

            list_of_optional_vulnerability.forEach((param_value) => {
                const requestResult = requestHtmlLength(url, {[url_param]: param_value})
                // console.log('request Result: ', requestResult)
                vulnerability_result.push(requestResult)
            })
            vulnerability_result = await Promise.all(vulnerability_result)
            vulnerability_result = Math.max(...vulnerability_result)
            console.log('vulnerability_result', vulnerability_result)

            let non_vulnerability_result = []

            list_of_legitc_values.forEach((param_value) => {
                const requestResult = requestHtmlLength(url, {[url_param]: param_value})
                // console.log('request Result: ', requestResult)
                non_vulnerability_result.push(requestResult)
            })
            non_vulnerability_result = await Promise.all(non_vulnerability_result)
            non_vulnerability_result = Math.max(...non_vulnerability_result)
            console.log('non_vulnerability_result', non_vulnerability_result)

            const diff = percDiff(non_vulnerability_result, vulnerability_result)
            return {
                paramName: url_param,
                isVula:    diff > 20 ? 'Yes' : 'No',
                precent:   Math.round(diff),
            }
        })
        paramater_result = await Promise.all(paramater_result)
        console.log('paramater_result: ', paramater_result)
        res.render('injectionTool', {title: 'injectionTool', result: paramater_result})
    }
})


async function requestHtmlLength(url, paramters) {
    try {
        const response = await axios.get(url, {params: paramters})
        if (response.status === 200) {
            const html = response.data
            return html.length
        }
        return 0
    } catch (e) {
        console.error(e)
    }
}

module.exports = defaultRoutes